// import axios from "axios";

// export const GetMember = async (setProp) => {
// 	const res = axios.get("");
// 	const data = res?.data;
//     setProp(data)
// };

// export const GetGroup = async (setProp) => {
// 	const res = axios.get("");
// 	const data = res?.data;
//     setProp(data)
// };

// export const GetClass = async (setProp) => {
// 	const res = axios.get("");
// 	const data = res?.data;
//     setProp(data)
// };

export const GetMember = async (setProp) => {
	setProp([
		{
			class: "12.11",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Nguyễn Văn An",
			id: "01",
			sex: "Nam",
			doanvien: true,
			birth: "20/05/2006",
			email: "userexampleemail@gmail.com",
			phone: "0192847261",
			fb: "userexamplefblink",
			ins: "userexampleinslink",
			score: 300,
		},
		{
			role: "Cán bộ",
			type: "Cá nhân",
			name: "Trần Thị Bình",
			id: "02",
			sex: "Nữ",
			doanvien: true,
			birth: "22/01/1994",
			email: "userexampleemail@gmail.com",
			phone: "0192847261",
			fb: "userexamplefblink",
			ins: "userexampleinslink",
			score: 300,
		},
		{
			class: "12.4",
			role: "Giáo viên",
			type: "Cá nhân",
			name: "Lê Văn Cường",
			id: "03",
			sex: "Nam",
			doanvien: true,
			birth: "06/12/1990",
			email: "userexampleemail@gmail.com",
			phone: "0192847261",
			fb: "userexamplefblink",
			ins: "userexampleinslink",
			score: 300,
		},
		{
			class: "10.7",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Phạm Thị Dũng",
			id: "04",
			sex: "Nữ",
			doanvien: true,
			birth: "10/11/2008",
			email: "userexampleemail@gmail.com",
			phone: "0192847261",
			fb: "userexamplefblink",
			ins: "userexampleinslink",
			score: 300,
		},
	]);
};

export const GetStudent = async (setProp) => {
	setProp([
		{
			class: "12.5",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Trần Minh Chi",
			id: "012345678",
			sex: "Nam",
			doanvien: true,
			birth: "2003-08-20",
			email: "user1exampleemail@gmail.com",
			phone: "0123456789",
			fb: "userexamplefblink1",
			ins: "userexampleinslink1",
			score: 400,
		},
		{
			class: "12.2",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Lê Thị Hương An",
			id: "123456789",
			sex: "Nữ",
			doanvien: true,
			birth: "2005-03-15",
			email: "user2exampleemail@gmail.com",
			phone: "0987654321",
			fb: "userexamplefblink2",
			ins: "userexampleinslink2",
			score: 400,
		},
		{
			class: "12.1",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Nguyễn Văn Bình",
			id: "234567890",
			sex: "Nam",
			doanvien: true,
			birth: "2004-11-02",
			email: "user3exampleemail@gmail.com",
			phone: "0129876543",
			fb: "userexamplefblink3",
			ins: "userexampleinslink3",
			score: 400,
		},
		{
			class: "12.8",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Phạm Thị Lan Dũng",
			id: "345678901",
			sex: "Nữ",
			doanvien: true,
			birth: "2002-07-28",
			email: "user4exampleemail@gmail.com",
			phone: "0983216547",
			fb: "userexamplefblink4",
			ins: "userexampleinslink4",
			score: 400,
		},
		{
			class: "12.6",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Võ Minh Hòa",
			id: "456789012",
			sex: "Nam",
			doanvien: true,
			birth: "2005-05-18",
			email: "user5exampleemail@gmail.com",
			phone: "0938765432",
			fb: "userexamplefblink5",
			ins: "userexampleinslink5",
			score: 400,
		},
		{
			class: "12.9",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Nguyễn Văn An",
			id: "567890123",
			sex: "Nam",
			doanvien: true,
			birth: "2006-02-19",
			email: "user6exampleemail@gmail.com",
			phone: "0965432198",
			fb: "userexamplefblink6",
			ins: "userexampleinslink6",
			score: 400,
		},
		{
			class: "12.7",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Lê Văn An",
			id: "987654321",
			sex: "Nam",
			doanvien: true,
			birth: "2004-04-05",
			email: "user16exampleemail@gmail.com",
			phone: "0865432179",
			fb: "userexamplefblink16",
			ins: "userexampleinslink16",
			score: 400,
		},
		{
			class: "12.3",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Phạm Thị Dũng",
			id: "876543210",
			sex: "Nữ",
			doanvien: true,
			birth: "2003-09-22",
			email: "user17exampleemail@gmail.com",
			phone: "0987654320",
			fb: "userexamplefblink17",
			ins: "userexampleinslink17",
			score: 400,
		},
		{
			class: "12.10",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Võ Minh Bình",
			id: "765432109",
			sex: "Nam",
			doanvien: true,
			birth: "2002-12-31",
			email: "user18exampleemail@gmail.com",
			phone: "0938765431",
			fb: "userexamplefblink18",
			ins: "userexampleinslink18",
			score: 400,
		},
		{
			class: "12.5",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Nguyễn Thị Lan",
			id: "654321098",
			sex: "Nữ",
			doanvien: true,
			birth: "2005-06-10",
			email: "user19exampleemail@gmail.com",
			phone: "0965432187",
			fb: "userexamplefblink19",
			ins: "userexampleinslink19",
			score: 400,
		},
		{
			class: "12.1",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Trần Văn Chi",
			id: "543210987",
			sex: "Nam",
			doanvien: true,
			birth: "2006-03-08",
			email: "user20exampleemail@gmail.com",
			phone: "0865432165",
			fb: "userexamplefblink20",
			ins: "userexampleinslink20",
			score: 400,
		},
		{
			class: "12.8",
			role: "Học sinh",
			type: "Cá nhân",
			name: "Lê Thị Hòa",
			id: "432109876",
			sex: "Nữ",
			doanvien: true,
			birth: "2004-11-14",
			email: "user21exampleemail@gmail.com",
			phone: "0987654309",
			fb: "userexamplefblink21",
			ins: "userexampleinslink21",
			score: 400,
		},
	]);
};

export const GetGroup = async (setProp) => {
	setProp([
		{
			role: "Nhóm thuộc quyền quản lí của nhà trường",
			type: "Nhóm",
			name: "Tuổi Trẻ Huỳnh Văn Nghệ",
			score: 300,
			id: "05",
			birth: "07/05/2024",
			totalMember: 789,
			monitor: "Nguyễn Văn K",
			field: "Các lĩnh vực/ chuyên ngành",
			goal: "Mục tiêu/ mục đích thành lập",
		},
		{
			role: "Nhóm thuộc quyền quản lí của nhà trường",
			type: "Nhóm",
			name: "Học Bá Tứ Hùng",
			score: 245,
			id: "06",
			birth: "07/05/2024",
			totalMember: 670,
			monitor: "Nguyễn Văn K",
			field: "Các lĩnh vực/ chuyên ngành",
			goal: "Mục tiêu/ mục đích thành lập",
		},
		{
			role: "Nhóm thuộc quyền quản lí của học sinh",
			type: "Nhóm",
			name: "Dân Chơi Học Vần",
			score: 215,
			id: "07",
			birth: "07/05/2024",
			totalMember: 320,
			monitor: "Nguyễn Văn K",
			field: "Các lĩnh vực/ chuyên ngành",
			goal: "Mục tiêu/ mục đích thành lập",
		},
		{
			role: "Nhóm thuộc quyền quản lí của học sinh",
			type: "Nhóm",
			name: "Băng Hậu Chém Gió",
			score: 200,
			id: "63",
			birth: "07/05/2024",
			totalMember: 310,
			monitor: "Nguyễn Văn K",
			field: "Các lĩnh vực/ chuyên ngành",
			goal: "Mục tiêu/ mục đích thành lập",
		},
		{
			role: "Nhóm thuộc quyền quản lí của học sinh",
			type: "Nhóm",
			name: "F4 Học Đường",
			score: 189,
			id: "124",
			birth: "07/05/2024",
			totalMember: 302,
			monitor: "Nguyễn Văn K",
			field: "Các lĩnh vực/ chuyên ngành",
			goal: "Mục tiêu/ mục đích thành lập",
		},
		{
			role: "Nhóm thuộc quyền quản lí của học sinh",
			type: "Nhóm",
			name: "Thánh Nhây Hội",
			score: 188,
			id: "1231",
			birth: "07/05/2024",
			totalMember: 297,
			monitor: "Nguyễn Văn K",
			field: "Các lĩnh vực/ chuyên ngành",
			goal: "Mục tiêu/ mục đích thành lập",
		},
		{
			role: "Nhóm thuộc quyền quản lí của học sinh",
			type: "Nhóm",
			name: "Chuyên Gia Chém Gió",
			score: 165,
			id: "42",
			birth: "07/05/2024",
			totalMember: 120,
			monitor: "Nguyễn Văn K",
			field: "Các lĩnh vực/ chuyên ngành",
			goal: "Mục tiêu/ mục đích thành lập",
		},
		{
			role: "Nhóm thuộc quyền quản lí của học sinh",
			type: "Nhóm",
			name: "Bà Tám Học Đường",
			score: 155,
			id: "11",
			birth: "07/05/2024",
			totalMember: 60,
			monitor: "Nguyễn Văn K",
			field: "Các lĩnh vực/ chuyên ngành",
			goal: "Mục tiêu/ mục đích thành lập",
		},
		{
			role: "Nhóm thuộc quyền quản lí của học sinh",
			type: "Nhóm",
			name: "Hội Chị Em Cà Khịa",
			score: 143,
			id: "22",
			birth: "07/05/2024",
			totalMember: 56,
			monitor: "Nguyễn Văn K",
			field: "Các lĩnh vực/ chuyên ngành",
			goal: "Mục tiêu/ mục đích thành lập",
		},
		{
			role: "Nhóm thuộc quyền quản lí của học sinh",
			type: "Nhóm",
			name: "Bộ Ba Siêu Quậy",
			score: 133,
			id: "421",
			birth: "07/05/2024",
			totalMember: 33,
			monitor: "Nguyễn Văn K",
			field: "Các lĩnh vực/ chuyên ngành",
			goal: "Mục tiêu/ mục đích thành lập",
		},
	]);
};

export const GetClass = async (setProp) => {
	setProp([
		{
			role: "Lớp học",
			type: "Lớp",
			name: "12.9",
			score: 300,
			id: "42",
			studyYear: "2023-2024",
			totalStudent: 37,
			boyOnGirl: "1/2",
			field: "KHTN",
			teacher: "Nguyễn Văn C",
			monitor: "Trần Văn K",
			viceMonitor: "Nguyễn Thị T",
		},
		{
			role: "Lớp học",
			type: "Lớp",
			name: "10.10",
			score: 299,
			id: "1",
			studyYear: "2023-2024",
			totalStudent: 34,
			boyOnGirl: "1/2",
			field: "Update later",
			teacher: "Nguyễn Văn C",
			monitor: "Trần Văn K",
			viceMonitor: "Nguyễn Thị T",
		},
		{
			role: "Lớp học",
			type: "Lớp",
			name: "12.11",
			score: 298,
			id: "52",
			studyYear: "2023-2024",
			totalStudent: 35,
			boyOnGirl: "1/2",
			field: "KHTN",
			teacher: "Nguyễn Văn C",
			monitor: "Trần Văn K",
			viceMonitor: "Nguyễn Thị T",
		},
		{
			role: "Lớp học",
			type: "Lớp",
			name: "11.8",
			score: 297,
			id: "12",
			studyYear: "2023-2024",
			totalStudent: 31,
			boyOnGirl: "1/2",
			field: "Update later",
			teacher: "Nguyễn Văn C",
			monitor: "Trần Văn K",
			viceMonitor: "Nguyễn Thị T",
		},
		{
			role: "Lớp học",
			type: "Lớp",
			name: "10.4",
			score: 296,
			id: "1124",
			studyYear: "2023-2024",
			totalStudent: 40,
			boyOnGirl: "1/2",
			field: "Update later",
			teacher: "Nguyễn Văn C",
			monitor: "Trần Văn K",
			viceMonitor: "Nguyễn Thị T",
		},
		{
			role: "Lớp học",
			type: "Lớp",
			name: "12.10",
			score: 295,
			id: "1242",
			studyYear: "2023-2024",
			totalStudent: 32,
			boyOnGirl: "1/2",
			field: "KHTN",
			teacher: "Nguyễn Văn C",
			monitor: "Trần Văn K",
			viceMonitor: "Nguyễn Thị T",
		},
		{
			role: "Lớp học",
			type: "Lớp",
			name: "10.8",
			score: 294,
			id: "112",
			studyYear: "2023-2024",
			totalStudent: 38,
			boyOnGirl: "1/2",
			field: "Update later",
			teacher: "Nguyễn Văn C",
			monitor: "Trần Văn K",
			viceMonitor: "Nguyễn Thị T",
		},
		{
			role: "Lớp học",
			type: "Lớp",
			name: "12.6",
			score: 293,
			id: "22",
			studyYear: "2023-2024",
			totalStudent: 30,
			boyOnGirl: "1/2",
			field: "KHXH",
			teacher: "Nguyễn Văn C",
			monitor: "Trần Văn K",
			viceMonitor: "Nguyễn Thị T",
		},
		{
			role: "Lớp học",
			type: "Lớp",
			name: "11.9",
			score: 291,
			id: "332",
			studyYear: "2023-2024",
			totalStudent: 37,
			boyOnGirl: "1/2",
			field: "Update later",
			teacher: "Nguyễn Văn C",
			monitor: "Trần Văn K",
			viceMonitor: "Nguyễn Thị T",
		},
		{
			role: "Lớp học",
			type: "Lớp",
			name: "10.3",
			score: 292,
			id: "11",
			studyYear: "2023-2024",
			totalStudent: 41,
			boyOnGirl: "1/2",
			field: "Update later",
			teacher: "Nguyễn Văn C",
			monitor: "Trần Văn K",
			viceMonitor: "Nguyễn Thị T",
		},
	]);
};
